DELETE FROM items;

INSERT INTO items (seller_id, photo, price, title, description, type, is_active, is_sold, is_featured)
VALUES (1,'https://i.ibb.co/DkFCHGQ/bed-frame.jpg', 199, 'White Bed With Drawers', 'An awesome bed for small space', 'bed frame', TRUE, TRUE, FALSE),
       (1,'https://i.ibb.co/zV1pdMg/bookshelf.jpg', 249, 'Tall Bookshelf', 'A nice wooden bookshelf', 'bookshelf', TRUE, FALSE, FALSE),
       (1,'https://i.ibb.co/xqF3YHX/chair-dining.jpg', 199, 'Ivory Dining Chair', 'Nice ivory fabric dining chairs(3 chairs)', 'chair', TRUE, FALSE, TRUE),
       (2,'https://i.ibb.co/tLWVK1N/chair-outdoor.jpg', 49, 'Outdoor Patio Chair', 'A nice patio chair', 'chair', TRUE, FALSE, FALSE),
       (2,'https://i.ibb.co/kh7pnmV/chair-sofa.jpg', 149, 'Blue Loveseat Sofa', 'A soft blue sofa. Perfect for a small condo', 'sofa', TRUE, FALSE, FALSE),
       (2,'https://i.ibb.co/whS23rV/chair.jpg', 399, 'Orange Velvet Chair', 'A mid-century modern single chair with soft orange velvet fabric', 'chair', TRUE, FALSE, FALSE),
       (3,'https://i.ibb.co/s9R62Gd/desk.jpg', 149, 'Office Desk', 'A solid wood desk. Pefect for your home office!', 'desk', TRUE, FALSE, FALSE),
       (3,'https://i.ibb.co/Bz2ynV7/dresser.jpg', 99, 'Colorful chest dresser', 'A colorful dresser for your kid!', 'storage', TRUE, FALSE, FALSE),
       (3,'https://i.ibb.co/6PNpj1Q/table-coffee.jpg', 89, 'Sleek Coffee Table', 'A modern coffee table with wood top', 'table', TRUE, FALSE, FALSE),
       (4,'https://i.ibb.co/v1RdnSg/table-dining.jpg', 499, 'Classy Dining Table', 'A classy dining table', 'table', TRUE, FALSE, FALSE),
       (4,'https://i.ibb.co/GQzGjnX/table-outdoor.jpg', 59, 'Marble Top Outdoor table', 'A small outdoor table with marble top', 'table', TRUE, FALSE, FALSE),
       (4,'https://i.ibb.co/YXRhV7M/tv-stand.jpg', 789, 'White TV Stand', 'A mid-century white tv stand. Lots of storage!', 'tv stand', TRUE, FALSE, FALSE),
       (5,'https://www.pexels.com/photo/bedroom-bulb-interior-decoration-lamp-545048/', 29, 'Simple Table Lamp', 'A simple lamp with rose gold finish.', 'lamp', TRUE, FALSE, FALSE),
       (5,'https://www.pexels.com/photo/white-bed-linen-on-bed-3675263/', 499, 'Grey Bed Frame', 'A modern bed frame', 'bed frame', TRUE, FALSE, FALSE),
       (5,'https://www.pexels.com/photo/white-and-silver-table-lamp-1176516/', 49, 'Silver Table Lamp', 'A lamp with silver body and white head', 'lamp', TRUE, FALSE, FALSE),
       (6,'https://www.pexels.com/photo/bedroom-3637740/', 999, 'Dark Grey Leather King Bed', 'A fancy bed...very fancy', 'bed frame', TRUE, FALSE, FALSE),
       (6,'https://www.pexels.com/photo/brown-wooden-shelf-and-beige-fabric-sofa-1125130/', 399, 'Gold Finish Bookshelf', 'Gold finish bookshelf', 'bookshelf', TRUE, FALSE, FALSE),
       (6,'https://www.pexels.com/photo/empty-white-chairs-beside-table-2995012/', 39, 'Modern Dining Chair', 'A comfy dining chair-white color', 'chair', TRUE, FALSE, FALSE),
       (7,'https://www.pexels.com/photo/folding-chairs-outdoors-1321910/', 29, 'Folding Outdoor Chair', 'A description for Murdered Unicorn', 'chair', TRUE, FALSE, FALSE),
       (7,'https://www.pexels.com/photo/2-seat-orange-leather-sofa-beside-wall-1866149/', 699, 'Leather Sofa', 'A description for Vibrant Piki', 'sofa', TRUE, FALSE, FALSE),
       (7,'https://www.pexels.com/photo/chair-comfort-contemporary-daylight-2082090/', 199, 'Contemporary Chair', 'A description for Confident Periwinkle', 'chair', TRUE, FALSE, FALSE),
       (8,'https://www.pexels.com/photo/black-study-lamp-on-black-table-159839/', 129, 'Black Desk', 'A Black Desk', 'desk', TRUE, FALSE, FALSE),
       (8,'https://www.pexels.com/photo/golden-frame-with-numbers-on-brick-wall-3952087/', 499, 'Vintage Drawers', 'An old drawer', 'storage', TRUE, FALSE, FALSE),
       (8,'https://www.pexels.com/photo/white-book-on-brown-round-table-2387754/', 39, 'Round Coffe Table', 'A description for Spicy Fire Hydrant', 'table', TRUE, FALSE, FALSE),
       (9,'https://www.pexels.com/photo/chairs-contemporary-design-dining-271696/', 149, 'Round Dining Table', 'A description for Blushing Cacti', 'table', TRUE, FALSE, FALSE),
       (9,'https://www.pexels.com/photo/wine-glasses-on-table-near-pillows-1705716/', 29, 'Outdoor Table', 'A folding outdoor table with a tray', 'table', TRUE, FALSE, FALSE),
       (9,'https://www.pexels.com/photo/dining-area-3144581/', 899, 'Big Dining Table', 'A large dining table with glossy finish', 'table', TRUE, FALSE, FALSE),
       (10,'https://www.pexels.com/photo/white-table-lamp-on-top-of-nightstand-2082092/', 19, 'Night Table', 'A small night table', 'table', TRUE, FALSE, FALSE),
       (10,'https://www.pexels.com/photo/interior-of-children-bedroom-with-wooden-furniture-and-toys-and-globe-placed-on-shelves-in-room-3932930/', 99, 'Rattan Drawers', 'A seaside rattan drawers', 'storage', TRUE, FALSE, FALSE),
       (10,'https://www.pexels.com/photo/black-metal-desk-lamp-1112598/', 29, 'Metal Lamp', 'A description for Curtain In A Castle', 'desk', TRUE, FALSE, FALSE),
       (11,'https://www.pexels.com/photo/apartment-armchair-chair-coffee-table-1148955/', 199, 'Vintage Armchair', 'Vintage Armchair', 'chair', TRUE, FALSE, FALSE),
       (11,'https://www.pexels.com/photo/apartment-couch-cozy-decor-198272/', 299, 'Funky Sofa', 'A corduroy loveseat', 'sofa', TRUE, FALSE, FALSE),
       (11,'https://www.pexels.com/photo/cemetery-chair-countryside-empty-116910/', 99, 'Vintage Chair', 'A description for Hecka Pink', 'chair', TRUE, FALSE, FALSE),
       (12,'https://www.pexels.com/photo/photo-of-black-chair-2762247/', 19, 'Simple Dining Chair', 'A Black dining chair', 'chair', TRUE, FALSE, FALSE),
       (12,'https://www.pexels.com/photo/brown-wooden-4-layer-rack-1853725/', 299, 'Industrial Bookshelf', 'An industrial bookshelf set', 'bookshelf', TRUE, FALSE, FALSE),
       (12,'https://www.pexels.com/photo/a-simple-bedroom-3659683/', 299, 'Tufted Queen Bed', 'your eye travels to its soaring upholstered headboard', 'bed frame', TRUE, FALSE, FALSE);
