DELETE FROM items;

INSERT INTO items (seller_id, photo, price, title, description, type, is_active, is_sold, is_featured)
VALUES (1,'https://i.ibb.co/DkFCHGQ/bed-frame.jpg', 199, 'White Bed With Drawers', 'An awesome bed for small space', 'beds', TRUE, TRUE, FALSE),
       (1,'https://i.ibb.co/zV1pdMg/bookshelf.jpg', 249, 'Tall Bookshelf', 'A nice wooden bookshelf', 'bookshelves', TRUE, FALSE, FALSE),
       (1,'https://i.ibb.co/xqF3YHX/chair-dining.jpg', 199, 'Ivory Dining Chair', 'Nice ivory fabric dining chairs(3 chairs)', 'chairs', TRUE, FALSE, TRUE),
       (2,'https://i.ibb.co/tLWVK1N/chair-outdoor.jpg', 49, 'Outdoor Patio Chair', 'A nice patio chair', 'chairs', TRUE, FALSE, FALSE),
       (2,'https://i.ibb.co/kh7pnmV/chair-sofa.jpg', 149, 'Blue Loveseat Sofa', 'A soft blue sofa. Perfect for a small condo', 'sofas', TRUE, FALSE, FALSE),
       (2,'https://i.ibb.co/whS23rV/chair.jpg', 399, 'Orange Velvet Chair', 'A mid-century modern single chair with soft orange velvet fabric', 'chairs', TRUE, FALSE, TRUE),
       (11,'https://i.ibb.co/s9R62Gd/desk.jpg', 149, 'Office Desk', 'A solid wood desk. Pefect for your home office!', 'desks', TRUE, FALSE, FALSE),
       (3,'https://i.ibb.co/Bz2ynV7/dresser.jpg', 99, 'Colorful chest dresser', 'A colorful dresser for your kid!', 'storage', TRUE, FALSE, TRUE),
       (3,'https://i.ibb.co/6PNpj1Q/table-coffee.jpg', 89, 'Sleek Coffee Table', 'A modern coffee table with wood top', 'tables', TRUE, FALSE, FALSE),
       (4,'https://i.ibb.co/v1RdnSg/table-dining.jpg', 499, 'Classy Dining Table', 'A classy dining table', 'tables', TRUE, FALSE, FALSE),
       (4,'https://i.ibb.co/GQzGjnX/table-outdoor.jpg', 59, 'Marble Top Outdoor table', 'A small outdoor table with marble top', 'tables', TRUE, FALSE, FALSE),
       (12,'https://i.ibb.co/YXRhV7M/tv-stand.jpg', 789, 'White TV Stand', 'A mid-century white tv stand. Lots of storage!', 'tv stands', TRUE, FALSE, TRUE),
       (5,'https://images.pexels.com/photos/545048/pexels-photo-545048.jpeg', 29, 'Simple Table Lamp', 'A simple lamp with rose gold finish.', 'lamps', TRUE, FALSE, TRUE),
       (5,'https://images.pexels.com/photos/3675263/pexels-photo-3675263.jpeg', 499, 'Grey Bed Frame', 'A modern bed frame', 'beds', TRUE, FALSE, FALSE),
       (15,'https://images.pexels.com/photos/1176516/pexels-photo-1176516.jpeg', 49, 'Silver Table Lamp', 'A lamp with silver body and white head', 'lamps', TRUE, FALSE, FALSE),
       (6,'https://images.pexels.com/photos/3637740/pexels-photo-3637740.jpeg', 999, 'Dark Grey Leather King Bed', 'A fancy bed...very fancy', 'beds', TRUE, FALSE, TRUE),
       (6,'https://images.pexels.com/photos/1125130/pexels-photo-1125130.jpeg', 399, 'Gold Finish Bookshelf', 'Gold finish bookshelf', 'bookshelves', TRUE, FALSE, TRUE),
       (6,'https://images.pexels.com/photos/2995012/pexels-photo-2995012.jpeg', 39, 'Modern Dining Chair', 'A comfy dining chair-white color', 'chairs', TRUE, FALSE, FALSE),
       (7,'https://images.pexels.com/photos/1321910/pexels-photo-1321910.jpeg', 29, 'Folding Outdoor Chair', 'A comfy Folding outdoor chair. Nice and light.', 'chairs', TRUE, FALSE, FALSE),
       (7,'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg', 699, 'Leather Sofa', 'A nice leather sofa', 'sofas', TRUE, FALSE, FALSE),
       (7,'https://images.pexels.com/photos/2082090/pexels-photo-2082090.jpeg', 199, 'Contemporary Chair', 'A description for Confident Periwinkle', 'chairs', TRUE, FALSE, TRUE),
       (8,'https://images.pexels.com/photos/159839/office-home-house-desk-159839.jpeg', 129, 'Black Desk', 'A Black Desk', 'desks', TRUE, FALSE, FALSE),
       (8,'https://images.pexels.com/photos/3952087/pexels-photo-3952087.jpeg', 499, 'Vintage Drawers', 'An old drawer', 'storage', TRUE, FALSE, TRUE),
       (8,'https://images.pexels.com/photos/2387754/pexels-photo-2387754.jpeg', 39, 'Round Coffe Table', 'A great coffee table', 'tables', TRUE, FALSE, TRUE),
       (9,'https://images.pexels.com/photos/271696/pexels-photo-271696.jpeg', 149, 'Round Dining Table', 'Perfect for 4 people', 'tables', TRUE, FALSE, TRUE),
       (9,'https://images.pexels.com/photos/1705716/pexels-photo-1705716.jpeg', 29, 'Outdoor Table', 'A folding outdoor table with a tray', 'tables', TRUE, FALSE, FALSE),
       (9,'https://images.pexels.com/photos/3144581/pexels-photo-3144581.jpeg', 899, 'Big Dining Table', 'A large dining table with glossy finish', 'tables', TRUE, FALSE, TRUE),
       (10,'https://images.pexels.com/photos/2082092/pexels-photo-2082092.jpeg', 19, 'Night Table', 'A small night table', 'tables', TRUE, FALSE, FALSE),
       (10,'https://images.pexels.com/photos/3932930/pexels-photo-3932930.jpeg', 99, 'Rattan Drawers', 'A seaside rattan drawers', 'storage', TRUE, FALSE, FALSE),
       (10,'https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg', 29, 'Metal Lamp', 'A description for Curtain In A Castle', 'lamps', TRUE, FALSE, FALSE),
       (11,'https://images.pexels.com/photos/1148955/pexels-photo-1148955.jpeg', 199, 'Vintage Armchair', 'Vintage Armchair from 1900s', 'chairs', TRUE, FALSE, FALSE),
       (11,'https://images.pexels.com/photos/198272/pexels-photo-198272.jpeg', 299, 'Funky Sofa', 'A corduroy loveseat', 'sofas', TRUE, FALSE, FALSE),
       (11,'https://images.pexels.com/photos/116910/pexels-photo-116910.jpeg', 99, 'Vintage Chair', 'A good choice for vintage lovers', 'chairs', TRUE, FALSE, FALSE),
       (12,'https://images.pexels.com/photos/2762247/pexels-photo-2762247.jpeg', 19, 'Simple Dining Chair', 'A Black dining chair', 'chairs', TRUE, FALSE, FALSE),
       (12,'https://images.pexels.com/photos/1853725/pexels-photo-1853725.jpeg', 299, 'Industrial Bookshelf', 'An industrial bookshelf set', 'bookshelves', TRUE, FALSE, TRUE),
       (12,'https://images.pexels.com/photos/3659683/pexels-photo-3659683.jpeg', 299, 'Tufted Queen Bed', 'your eye travels to its soaring upholstered headboard', 'beds', TRUE, FALSE, TRUE);

